services:
  scep:
    build:
      context: .
      dockerfile: scep/Dockerfile
    container_name: nanomdm-scep
    volumes:
      - ./scep/depot:/app/depot
    environment:
      - SCEP_CHALLENGE=nanomdm
      - SCEP_PORT=8080
      - SCEP_ALLOWRENEW=0
      - SCEP_DEBUG=true
      - SCEP_CERT_RENEW=0
    networks:
      - nanomdm
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scep.rule=Host(`scep.golain.io`)"
      - "traefik.http.routers.scep.entrypoints=websecure"
      - "traefik.http.routers.scep.tls=true"
      - "traefik.http.routers.scep.tls.certresolver=le"
      - "traefik.http.services.scep.loadbalancer.server.port=8080"

  # NanoMDM Server with PostgreSQL
  nanomdm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nanomdm-server
    environment:
      - NANOMDM_DEBUG=true
      - NANOMDM_LISTEN=:9000
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - nanomdm
      - proxy
      - queue
    depends_on:
      - scep
    restart: unless-stopped
    command:
      - "/app/nanomdm"
      - "-ca"
      - "/app/ca.pem"
      - "-api"
      - "API key"
      - "-debug"
      - "-storage"
      - "pgsql"
      - "-storage-dsn"
      - "postgres://nanomdm:<password>@<host>:5432/nanomdm?sslmode=require"
      - "-amqps-conn"
      - "amqps://rabbitmq:ef19e2ji@queue:5671/"
      - "-amqps-ca-cert"
      - "/app/certs/rabbitmq-ca.pem"
      - "-amqps-client-cert"
      - "/app/certs/rabbitmq-client.pem"
      - "-amqps-client-key"
      - "/app/certs/rabbitmq-client.key"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nanomdm.rule=Host(`nanomdm.golain.io`)"
      - "traefik.http.routers.nanomdm.entrypoints=websecure"
      - "traefik.http.routers.nanomdm.tls=true"
      - "traefik.http.routers.nanomdm.tls.certresolver=le"
      - "traefik.http.services.nanomdm.loadbalancer.server.port=9000"

networks:
  nanomdm:
    external: true
  proxy:
    external: true
  queue:
    external: true
