FROM golang:1.22 as build

WORKDIR /src

# TARGETARCH is set by Docker Buildx (e.g. amd64, arm64)
ARG TARGETARCH=amd64
ARG TARGETOS=linux

# Preload modules
COPY go.mod go.sum ./
RUN go mod download

# Build dep-broker
COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH:-amd64} \
    go build -tags netgo -ldflags "-s -w" -o /out/dep-broker ./cmd/dep-broker

FROM gcr.io/distroless/static
WORKDIR /app
COPY --from=build /out/dep-broker /app/dep-broker
EXPOSE 9010
ENTRYPOINT ["/app/dep-broker"]


